import test from 'node:test'
import assert from 'node:assert'
import { Bytes } from './parse'
import { CmdBase } from './cmd'
import {
  InternationalCharacterSet,
  PaperSensor,
  BuzzerSoundPattern,
  PeripheralDeviceSelection,
  UserDefinedCharacterSetSelection,
  BitImageMode,
  UnderlineMode,
  SimpleUnderlineMode,
  EmphasizedMode,
  CharacterFont,
  WhiteAndBlackReversePrintMode,
  Justification,
  CutShape,
  DoubleWidthMode,
  DoubleHeightMode,
  HorizontalTab,
  SetCharacterSpacing,
  SelectPrintMode,
  SetAbsolutePrintPosition,
  SelectOrCancelUserDefinedCharacterSet,
  DefineUserDefinedCharacters,
  ModelSpecificBuzzerControl,
  SelectBitImageMode,
  SetUnderlineMode,
  SelectDefaultLineSpacing,
  SetLineSpacing,
  SelectPeripheralDevice,
  CancelUserDefinedCharacters,
  InitializePrinter,
  SetHorizontalTabPositions,
  SetEmphasizedMode,
  SetDoubleStrikeMode,
  PrintAndFeedPaper,
  SelectPageMode,
  SelectCharacterFont,
  SelectInternationalCharacterSet,
  SelectStandardMode,
  SelectPrintDirectionInPageMode,
  SetRotationMode,
  SetPrintAreaInPageMode,
  SetRelativePrintPosition,
  SelectJustification,
  SelectPaperSensorsToOutputPaperEndSignals,
  SelectPaperSensorsToStopPrinting,
  EnableOrDisablePanelButtons,
  PrintAndFeedNLines,
  PartialCutOnePointLeftUncut,
  PartialCutThreePointsLeftUncut,
  GeneratePulse,
  SelectCharacterCodeTable,
  TransmitPeripheralDeviceStatus,
  TransmitPaperSensorStatus,
  SetUpsideDownPrintMode,
  SelectKanjiCharacterFont,
  CancelSetValuesForTopOrBottomLogoPrinting,
  TransmitSetValuesForTopOrBottomLogoPrinting,
  SetTopLogoPrinting,
  SetBottomLogoPrinting,
  MakeExtendedSettingsForTopOrBottomLogoPrinting,
  EnableOrDisableTopOrBottomLogoPrinting,
  SelectCharacterSize,
  SetWhiteAndBlackReversePrintMode,
  CutPaper,
  FeedAndCutPaper,
  parse,
  DoubleStrikeMode,
  PrintAndLineFeed,
  PrintAndReturnToStandardMode,
  PrintAndCarriageReturn,
  dle_eot,
  dle_enq,
  dle_dc4_fn1,
  dle_dc4_fn2,
  dle_dc4_fn3,
  dle_dc4_fn8,
  can,
  fs_exclamation,
  fs_ampersand,
  fs_minus,
  fs_period,
  fs_2,
  fs_cc,
  fs_cs,
  fs_cw,
  fs_lg_1,
  fs_lg_2,
  fs_lp,
  fs_lq,
  gs_dollarssign,
  gs_lparen_ca,
  gs_lparen_cd,
  gs_lparen_ce,
  gs_lparen_ce_fn01,
  gs_lparen_ce_fn02,
  gs_lparen_ce_fn05,
  gs_lparen_ce_fn06,
  gs_lparen_ce_fn11,
  gs_lparen_ce_fn12,
  gs_lparen_ce_fn13,
  gs_lparen_ce_fn14,
  gs_lparen_ce_fn15,
  gs_lparen_ce_fn16,
  gs_lparen_ch,
  gs_lparen_ch_fn48,
  gs_lparen_ck,
  gs_lparen_ck_fn50,
  gs_lparen_ck_fn97,
  gs_lparen_cl,
  gs_lparen_cl_fn48,
  gs_lparen_cl_fn50,
  gs_lparen_cl_fn51,
  gs_lparen_cl_fn52,
  gs_lparen_cl_fn64,
  gs_lparen_cl_fn65,
  gs_lparen_cl_fn66,
  gs_lparen_cl_fn67,
  gs_lparen_cl_fn69,
  gs_lparen_cl_fn80,
  gs_lparen_cl_fn81,
  gs_lparen_cl_fn82,
  gs_lparen_cl_fn83,
  gs_lparen_cl_fn85,
  gs_lparen_cl_fn112,
  gs_lparen_lk,
  gs_lparen_lk_fn065,
  gs_lparen_lk_fn066,
  gs_lparen_lk_fn067,
  gs_lparen_lk_fn068,
  gs_lparen_lk_fn069,
  gs_lparen_lk_fn070,
  gs_lparen_lk_fn080,
  gs_lparen_lk_fn081,
  gs_lparen_lk_fn082,
  gs_lparen_lk_fn165,
  gs_lparen_lk_fn167,
  gs_lparen_lk_fn169,
  gs_lparen_lk_fn180,
  gs_lparen_lk_fn181,
  gs_lparen_lk_fn182,
  gs_lparen_lk_fn265,
  gs_lparen_lk_fn280,
  gs_lparen_lk_fn281,
  gs_lparen_lk_fn282,
  gs_lparen_lk_fn367,
  gs_lparen_lk_fn371,
  gs_lparen_lk_fn380,
  gs_lparen_lk_fn381,
  gs_lparen_lk_fn382,
  gs_lparen_lk_fn467,
  gs_lparen_lk_fn471,
  gs_lparen_lk_fn472,
  gs_lparen_lk_fn480,
  gs_lparen_lk_fn481,
  gs_lparen_lk_fn482,
  gs_asterisk,
  gs_slash,
  gs_colon,
  gs_cd,
  gs_cd_fn67,
  gs_cd_fn83,
  gs_ch,
  gs_ci,
  gs_cl,
  gs_cp,
  gs_cw,
  gs_backslash,
  gs_caret,
  gs_la,
  gs_lb,
  gs_lf,
  gs_lg_0,
  gs_lg_2,
  gs_lh,
  gs_lk,
  gs_lr,
  gs_lv_0,
  gs_lw,
  PrintDirection,
  ClockwiseRotationMode,
  UpsideDownPrintMode,
} from './index'

type TestCase = {
  cmd: CmdBase
  bytes?: Buffer
  checks?: object
}

const testCases: TestCase[] = [
  {
    cmd: new HorizontalTab(),
    bytes: Buffer.from([0x09]),
  },
  {
    cmd: new SetCharacterSpacing(16),
    bytes: Buffer.from([0x1b, 0x20, 0x10]),
    checks: {
      n: 16,
    },
  },
  {
    cmd: new SelectPrintMode(
      CharacterFont.B,
      EmphasizedMode.On,
      SimpleUnderlineMode.On,
      DoubleWidthMode.On,
      DoubleHeightMode.On,
    ),
    bytes: Buffer.from([0x1b, 0x21, 0b10111001]),
    checks: {
      n: 0b10111001,
    },
  },
  {
    cmd: new SetAbsolutePrintPosition(0x0201),
    bytes: Buffer.from([0x1b, 0x24, 0x01, 0x02]),
    checks: {
      n: 0x0201,
    },
  },
  {
    cmd: new SelectOrCancelUserDefinedCharacterSet(
      UserDefinedCharacterSetSelection.Selected,
    ),
    bytes: Buffer.from([0x1b, 0x25, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new DefineUserDefinedCharacters(32, [
      Buffer.from([0x00, 0x0ff, 0x00, 0xff, 0x00, 0xff]),
      Buffer.from([]),
      Buffer.from([0xff, 0xff]),
    ]),
    bytes: Buffer.from([
      0x1b, 0x26, 0x03, 0x20, 0x22, 0x02, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff,
      0x00, 0x01, 0xff, 0xff, 0x00,
    ]),
    checks: {
      y: 3,
      c1: 32,
      c2: 34,
      bufs: [
        Buffer.from([0x02, 0x00, 0x0ff, 0x00, 0xff, 0x00, 0xff]),
        Buffer.from([0x00]),
        Buffer.from([0x01, 0xff, 0xff, 0x00]),
      ],
    },
  },
  {
    cmd: new ModelSpecificBuzzerControl(BuzzerSoundPattern.A, 2),
    bytes: Buffer.from([0x1b, 0x28, 0x41, 0x03, 0x00, 0x61, 0x01, 0x02]),
    checks: {
      p: 3,
      fn: 97,
      n: 1,
      c: 2,
    },
  },
  {
    cmd: new SelectBitImageMode(
      BitImageMode.EightDotSingleDensity,
      Buffer.from([0x05, 0x06, 0x07]),
    ),
    bytes: Buffer.from([0x1b, 0x2a, 0x01, 0x03, 0x00, 0x05, 0x06, 0x07]),
    checks: {
      m: 1,
      n: 3,
      d: Buffer.from([0x05, 0x06, 0x07]),
    },
  },
  {
    cmd: new SetUnderlineMode(UnderlineMode.OneDotThick),
    bytes: Buffer.from([0x1b, 0x2d, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new SelectDefaultLineSpacing(),
    bytes: Buffer.from([0x1b, 0x32]),
  },
  {
    cmd: new SetLineSpacing(1),
    bytes: Buffer.from([0x1b, 0x33, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new SelectPeripheralDevice(PeripheralDeviceSelection.EnablePrinter),
    bytes: Buffer.from([0x1b, 0x3d, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new CancelUserDefinedCharacters(32),
    bytes: Buffer.from([0x1b, 0x3f, 0x20]),
    checks: {
      n: 32,
    },
  },
  {
    cmd: new InitializePrinter(),
    bytes: Buffer.from([0x1b, 0x40]),
  },
  {
    cmd: new SetHorizontalTabPositions(8, 16, 32),
    bytes: Buffer.from([0x1b, 0x44, 8, 16, 32, 0]),
    checks: {
      buf: Buffer.from([8, 16, 32, 0]),
    },
  },
  {
    cmd: new SetEmphasizedMode(EmphasizedMode.On),
    bytes: Buffer.from([0x1b, 0x45, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new SetDoubleStrikeMode(DoubleStrikeMode.On),
    bytes: Buffer.from([0x1b, 0x47, 0x01]),
    checks: {
      n: 0x01,
    },
  },
  {
    cmd: new PrintAndFeedPaper(250),
    bytes: Buffer.from([0x1b, 0x4a, 0xfa]),
    checks: {
      n: 250,
    },
  },
  {
    cmd: new SelectPageMode(),
    bytes: Buffer.from([0x1b, 0x4c]),
  },
  {
    cmd: new SelectCharacterFont(CharacterFont.B),
    bytes: Buffer.from([0x1b, 0x4d, 0x01]),
    checks: {
      n: 0x01,
    },
  },
  {
    cmd: new SelectInternationalCharacterSet(InternationalCharacterSet.Japan),
    bytes: Buffer.from([0x1b, 0x52, 0x08]),
    checks: {
      n: 8,
    },
  },
  {
    cmd: new SelectStandardMode(),
    bytes: Buffer.from([0x1b, 0x53]),
  },
  {
    cmd: new SelectPrintDirectionInPageMode(PrintDirection.RightToLeft),
    bytes: Buffer.from([0x1b, 0x54, 0x2]),
    checks: {
      n: 2,
    },
  },
  {
    cmd: new SetRotationMode(ClockwiseRotationMode.OneDotSpacing),
    bytes: Buffer.from([0x1b, 0x56, 0x1]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new SetPrintAreaInPageMode(0xabcd, 0xef12, 0x3456, 0x6789),
    bytes: Buffer.from([
      0x1b, 0x57, 0xcd, 0xab, 0x12, 0xef, 0x56, 0x34, 0x89, 0x67,
    ]),
    checks: {
      x: 0xabcd,
      y: 0xef12,
      dx: 0x3456,
      dy: 0x6789,
    },
  },
  { cmd: new SetRelativePrintPosition() },
  {
    cmd: new SelectJustification(Justification.Center),
    bytes: Buffer.from([0x1b, 0x61, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new SelectPaperSensorsToOutputPaperEndSignals([
      PaperSensor.NearEnd,
      PaperSensor.End,
    ]),
    bytes: Buffer.from([0x1b, 0x63, 0x33, 0b0101]),
    checks: {
      n: 0b0101,
    },
  },
  {
    cmd: new SelectPaperSensorsToStopPrinting([
      PaperSensor.NearEnd,
      PaperSensor.End,
    ]),
    bytes: Buffer.from([0x1b, 0x63, 0x34, 0b0101]),
    checks: {
      n: 0b0101,
    },
  },
  { cmd: new EnableOrDisablePanelButtons() },
  {
    cmd: new PrintAndFeedNLines(1),
    bytes: Buffer.from([0x1b, 0x64, 0x01]),
    checks: {
      n: 1,
    },
  },
  { cmd: new PartialCutOnePointLeftUncut(), bytes: Buffer.from([0x1b, 0x69]) },
  {
    cmd: new PartialCutThreePointsLeftUncut(),
    bytes: Buffer.from([0x1b, 0x6d]),
  },
  { cmd: new GeneratePulse() },
  { cmd: new SelectCharacterCodeTable() },
  { cmd: new TransmitPeripheralDeviceStatus() },
  { cmd: new TransmitPaperSensorStatus() },
  {
    cmd: new SetUpsideDownPrintMode(UpsideDownPrintMode.On),
    bytes: Buffer.from([0x1b, 0x7b, 0x1]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new SelectKanjiCharacterFont(0),
    bytes: Buffer.from([0x1c, 0x28, 0x41, 0x02, 0x00, 0x30, 0x00]),
    checks: {
      p: 2,
      fn: 0x30,
      m: 0,
    },
  },
  {
    cmd: new CancelSetValuesForTopOrBottomLogoPrinting(0x30),
    bytes: Buffer.from([
      0x1c, 0x28, 0x45, 0x06, 0x00, 0x3c, 0x02, 0x30, 0x43, 0x4c, 0x52,
    ]),
    checks: {
      p: 6,
      fn: 0x3c,
      m: 2,
      c: 0x30,
      d1: 0x43,
      d2: 0x4c,
      d3: 0x52,
    },
  },
  {
    cmd: new TransmitSetValuesForTopOrBottomLogoPrinting(0x30),
    bytes: Buffer.from([0x1c, 0x28, 0x45, 0x03, 0x00, 0x3d, 0x02, 0x30]),
    checks: {
      p: 3,
      fn: 0x3d,
      m: 2,
      c: 0x30,
    },
  },
  {
    cmd: new SetTopLogoPrinting(0x20, 0x20, 0x30, 0x00),
    bytes: Buffer.from([
      0x1c, 0x28, 0x45, 0x06, 0x00, 0x3e, 0x02, 0x20, 0x20, 0x30, 0x00,
    ]),
    checks: {
      p: 6,
      fn: 0x3e,
      m: 2,
      kc1: 0x20,
      kc2: 0x20,
      a: 0x30,
      n: 0x00,
    },
  },
  {
    cmd: new SetBottomLogoPrinting(0x20, 0x20, 0x30),
    bytes: Buffer.from([
      0x1c, 0x28, 0x45, 0x05, 0x00, 0x3f, 0x02, 0x20, 0x20, 0x30,
    ]),
    checks: {
      p: 5,
      fn: 0x3f,
      m: 2,
      kc1: 0x20,
      kc2: 0x20,
      a: 0x30,
    },
  },
  {
    cmd: new MakeExtendedSettingsForTopOrBottomLogoPrinting(
      6,
      Buffer.from([0x30, 0x31, 0x40, 0x30]),
    ),
    bytes: Buffer.from([
      0x1c, 0x28, 0x45, 0x06, 0x00, 0x40, 0x02, 0x30, 0x31, 0x40, 0x30,
    ]),
    checks: {
      p: 6,
      fn: 0x40,
      m: 2,
      settings: Buffer.from([0x30, 0x31, 0x40, 0x30]),
    },
  },
  {
    cmd: new EnableOrDisableTopOrBottomLogoPrinting(0x30, 0x30),
    bytes: Buffer.from([0x1c, 0x28, 0x45, 0x04, 0x00, 0x41, 0x02, 0x30, 0x30]),
    checks: {
      p: 4,
      fn: 0x41,
      m: 2,
      a: 0x30,
      n: 0x30,
    },
  },
  {
    cmd: new SelectCharacterSize({ width: 2, height: 3 }),
    bytes: Buffer.from([0x1d, 0x21, 0x12]),
    checks: {
      n: 18,
    },
  },
  {
    cmd: new SetWhiteAndBlackReversePrintMode(WhiteAndBlackReversePrintMode.On),
    bytes: Buffer.from([0x1d, 0x42, 0x01]),
    checks: {
      n: 1,
    },
  },
  {
    cmd: new CutPaper(CutShape.PartialCut),
    bytes: Buffer.from([0x1d, 0x56, 0x01]),
    checks: {
      m: 1,
    },
  },
  {
    cmd: new FeedAndCutPaper(255, CutShape.PartialCut),
    bytes: Buffer.from([0x1d, 0x56, 0x42, 0xff]),
    checks: {
      m: 66,
      n: 255,
    },
  },
  {
    cmd: new PrintAndLineFeed(),
    bytes: Buffer.from([0x0a]),
  },
  {
    cmd: new PrintAndReturnToStandardMode(),
    bytes: Buffer.from([0x0c]),
  },
  { cmd: new PrintAndCarriageReturn(), bytes: Buffer.from([0x0d]) },
  { cmd: new dle_eot() },
  { cmd: new dle_enq() },
  { cmd: new dle_dc4_fn1() },
  { cmd: new dle_dc4_fn2() },
  { cmd: new dle_dc4_fn3() },
  { cmd: new dle_dc4_fn8() },
  { cmd: new can() },
  { cmd: new fs_exclamation() },
  { cmd: new fs_ampersand() },
  { cmd: new fs_minus() },
  { cmd: new fs_period() },
  { cmd: new fs_2() },
  { cmd: new fs_cc() },
  { cmd: new fs_cs() },
  { cmd: new fs_cw() },
  { cmd: new fs_lg_1() },
  { cmd: new fs_lg_2() },
  { cmd: new fs_lp() },
  { cmd: new fs_lq() },
  { cmd: new gs_dollarssign() },
  { cmd: new gs_lparen_ca() },
  { cmd: new gs_lparen_cd() },
  { cmd: new gs_lparen_ce() },
  { cmd: new gs_lparen_ce_fn01() },
  { cmd: new gs_lparen_ce_fn02() },
  { cmd: new gs_lparen_ce_fn05() },
  { cmd: new gs_lparen_ce_fn06() },
  { cmd: new gs_lparen_ce_fn11() },
  { cmd: new gs_lparen_ce_fn12() },
  { cmd: new gs_lparen_ce_fn13() },
  { cmd: new gs_lparen_ce_fn14() },
  { cmd: new gs_lparen_ce_fn15() },
  { cmd: new gs_lparen_ce_fn16() },
  { cmd: new gs_lparen_ch() },
  { cmd: new gs_lparen_ch_fn48() },
  { cmd: new gs_lparen_ck() },
  { cmd: new gs_lparen_ck_fn50() },
  { cmd: new gs_lparen_ck_fn97() },
  { cmd: new gs_lparen_cl() },
  { cmd: new gs_lparen_cl_fn48() },
  { cmd: new gs_lparen_cl_fn50() },
  { cmd: new gs_lparen_cl_fn51() },
  { cmd: new gs_lparen_cl_fn52() },
  { cmd: new gs_lparen_cl_fn64() },
  { cmd: new gs_lparen_cl_fn65() },
  { cmd: new gs_lparen_cl_fn66() },
  { cmd: new gs_lparen_cl_fn67() },
  { cmd: new gs_lparen_cl_fn69() },
  { cmd: new gs_lparen_cl_fn80() },
  { cmd: new gs_lparen_cl_fn81() },
  { cmd: new gs_lparen_cl_fn82() },
  { cmd: new gs_lparen_cl_fn83() },
  { cmd: new gs_lparen_cl_fn85() },
  { cmd: new gs_lparen_cl_fn112() },
  { cmd: new gs_lparen_lk() },
  { cmd: new gs_lparen_lk_fn065() },
  { cmd: new gs_lparen_lk_fn066() },
  { cmd: new gs_lparen_lk_fn067() },
  { cmd: new gs_lparen_lk_fn068() },
  { cmd: new gs_lparen_lk_fn069() },
  { cmd: new gs_lparen_lk_fn070() },
  { cmd: new gs_lparen_lk_fn080() },
  { cmd: new gs_lparen_lk_fn081() },
  { cmd: new gs_lparen_lk_fn082() },
  { cmd: new gs_lparen_lk_fn165() },
  { cmd: new gs_lparen_lk_fn167() },
  { cmd: new gs_lparen_lk_fn169() },
  { cmd: new gs_lparen_lk_fn180() },
  { cmd: new gs_lparen_lk_fn181() },
  { cmd: new gs_lparen_lk_fn182() },
  { cmd: new gs_lparen_lk_fn265() },
  { cmd: new gs_lparen_lk_fn280() },
  { cmd: new gs_lparen_lk_fn281() },
  { cmd: new gs_lparen_lk_fn282() },
  { cmd: new gs_lparen_lk_fn367() },
  { cmd: new gs_lparen_lk_fn371() },
  { cmd: new gs_lparen_lk_fn380() },
  { cmd: new gs_lparen_lk_fn381() },
  { cmd: new gs_lparen_lk_fn382() },
  { cmd: new gs_lparen_lk_fn467() },
  { cmd: new gs_lparen_lk_fn471() },
  { cmd: new gs_lparen_lk_fn472() },
  { cmd: new gs_lparen_lk_fn480() },
  { cmd: new gs_lparen_lk_fn481() },
  { cmd: new gs_lparen_lk_fn482() },
  { cmd: new gs_asterisk() },
  { cmd: new gs_slash() },
  { cmd: new gs_colon() },
  { cmd: new gs_cd() },
  { cmd: new gs_cd_fn67() },
  { cmd: new gs_cd_fn83() },
  { cmd: new gs_ch() },
  { cmd: new gs_ci() },
  { cmd: new gs_cl() },
  { cmd: new gs_cp() },
  { cmd: new gs_cw() },
  { cmd: new gs_backslash() },
  { cmd: new gs_caret() },
  { cmd: new gs_la() },
  { cmd: new gs_lb() },
  { cmd: new gs_lf() },
  { cmd: new gs_lg_0() },
  { cmd: new gs_lg_2() },
  { cmd: new gs_lh() },
  { cmd: new gs_lk() },
  { cmd: new gs_lr() },
  { cmd: new gs_lv_0() },
  { cmd: new gs_lw() },
]

for (const testCase of testCases) {
  void test(testCase.cmd.toString(), (t) => {
    if (!testCase.bytes) {
      t.skip()
      return
    }

    let cmds = parse(testCase.bytes)
    cmds = cmds.filter((cmd) => !(cmd instanceof Bytes))
    assert.strictEqual(cmds.length, 1, 'failed to parse a command')
    const parsedCmd = cmds[0]
    assert(parsedCmd instanceof CmdBase)
    assert(parsedCmd.isValid)

    assert(
      testCase.cmd.isValid,
      'this.validate() must be called at the end of the subclass constructor',
    )
    assert.deepStrictEqual(
      parsedCmd,
      testCase.cmd,
      'parsed (actual) differs from constructed (expected)',
    )

    for (const [key, value] of Object.entries(testCase.checks ?? {})) {
      assert.deepStrictEqual(
        parsedCmd[key],
        value,
        `member ${key} is ${parsedCmd[key]}, but expected ${value}`,
      )
    }

    const buf = parsedCmd.serialize()
    assert.deepStrictEqual(buf, testCase.bytes)
  })
}
